use_frameworks!

platform :ios, '9.0'

target 'MLFoundationLib_Example' do
  pod 'MLFoundationLib', :path => '../'
  pod 'Masonry', :git => 'https://github.com/SnapKit/Masonry.git'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Colours'
  pod 'ReactiveObjC'
  pod 'YBImageBrowser/Video'
  pod 'FMDB'
  pod 'MJRefresh'
  pod 'MMKV'
  pod 'Logan', '~> 1.2.5'

  pod 'Texture', :git => 'https://gitee.com/qq912276337/Texture.git',:tag => '2.8'
#  pod 'AsyncDisplayKit', :git => 'https://gitee.com/qq912276337/Texture.git',:tag => '2.8.1'

end
